#!/usr/bin/bash

search_directory="./"

while getopts 'g:' flag; do
  case "${flag}" in
    g) search_directory="$HOME";;
  esac
done

selected_file=$(find $search_directory -type f | fzf --preview "batcat --color=always --style=numbers --line-range=:500 {}")

echo $selected_file

if [[ -z $selected_file ]]; then
  exit 0
fi

nvim $selected_file

