#!/usr/bin/bash

if [[ $# -eq 1 ]];then
selected=$1
else
selected=$(tmux ls -F "#{session_name}" | fzf)
fi

session_to_switch=$(tmux ls | sed -n '/(attached)/!s/:.*//p' | head -n 1)

if [[ ! -z $session_to_switch ]];then
  tmux switch-client -t $session_to_switch
fi

if [[ -z selected ]]
then
  exit 0
fi

tmux kill-session -t $selected
